bagIds = {
	[ 1] = {n = 'energyDrink_Basic'},
	[ 2] = {n = 'energyDrink_Mega'},
	[ 3] = {n = 'energyDrink_Ultra'},
	[ 4] = {n = 'pickaxe', blockUse = true},
	[ 5] = {n = 'clock'},
	[ 6] = {n = 'milk'},
	[ 7] = {n = 'goldNugget', blockUse = true},
	[ 8] = {n = 'dynamite'},
	[ 9] = {n = 'shrinkPotion'},
	[10] = {n = 'growthPotion'},
	[11] = {n = 'coffee'},
	[12] = {n = 'hotChocolate'},
	[13] = {n = 'milkShake'},
	[14] = {n = 'seed'},
	[15] = {n = 'fertilizer'},
	[16] = {n = 'water'},
	[17] = {n = 'tomato'},
	[18] = {n = 'tomatoSeed'},
	[19] = {n = 'oregano'},
	[20] = {n = 'oreganoSeed'},
	[21] = {n = 'lemon'},
	[22] = {n = 'lemonSeed'},
	[23] = {n = 'salt'},
	[24] = {n = 'pepper'},
	[25] = {n = 'pepperSeed'},
	[26] = {n = 'luckyFlower'},
	[27] = {n = 'luckyFlowerSeed'},
	[28] = {n = 'sauce'},
	[29] = {n = 'hotsauce'},
	[30] = {n = 'dough'},
	[31] = {n = 'wheat'},
	[32] = {n = 'wheatSeed'},
	[33] = {n = 'pizza'},
	[34] = {n = 'cornFlakes'},
	[35] = {n = 'pumpkin'},
	[36] = {n = 'pumpkinSeed'},
	[37] = {n = 'superFertilizer'},
	[38] = {n = 'cookies'},
	[39] = {n = 'sugar'},
	[40] = {n = 'chocolate'},
	[41] = {n = 'blueberries'},
	[42] = {n = 'blueberriesSeed'},
	[43] = {n = 'cheese'},
	[44] = {n = 'fish_SmoltFry'},
	[45] = {n = 'fish_Lionfish'},
	[46] = {n = 'fish_Dogfish'},
	[47] = {n = 'fish_Catfish'},
	[48] = {n = 'fish_RuntyGuppy'},
	[49] = {n = 'fish_Lobster'},
	[50] = {n = 'fish_Goldenmare'},
	[51] = {n = 'fish_Frog'},
	[52] = {n = 'lemonade'},
	[53] = {n = 'lobsterBisque'},
	[54] = {n = 'bread'},
	[55] = {n = 'bruschetta'},
	[56] = {n = 'waffles'},
	[57] = {n = 'egg'},
	[58] = {n = 'honey'},
	[59] = {n = 'grilledLobster'},
	[60] = {n = 'frogSandwich'},
	[61] = {n = 'chocolateCake'},
	[62] = {n = 'wheatFlour'},
	[63] = {n = 'salad'},
	[64] = {n = 'lettuce'},
	[65] = {n = 'pierogies'},
	[66] = {n = 'potato'},
	[67] = {n = 'frenchFries'},
	[68] = {n = 'pudding'},
	[69] = {n = 'garlicBread'},
	[70] = {n = 'garlic'},
	[71] = {n = 'blueprint', blockUse = true},
	[72] = {n = 'crystal_yellow', blockUse = true},
	[73] = {n = 'crystal_blue', blockUse = true},
	[74] = {n = 'crystal_purple', blockUse = true},
	[75] = {n = 'crystal_green', blockUse = true},
	[76] = {n = 'crystal_red', blockUse = true},
	[77] = {n = 'banana'},
	[78] = {n = 'bananaSeed'},
	[79] = {n = 'moqueca'},
	[80] = {n = 'grilledCheese'},
	[81] = {n = 'fishBurger'},
	[82] = {n = 'sushi'},
	[83] = {n = 'bananaCake'},
	[84] = {n = 'croquettes'},
	[85] = {n = 'meat'},
	[86] = {n = 'mushroom'},
	[87] = {n = 'cheeseburger'},
	[88] = {n = 'lasagna'},
	[89] = {n = 'meatballs'},
	[90] = {n = 'garlicMashedPotatoes'},
	[91] = {n = 'mushroomBurger'},
	[92] = {n = 'creamOfMushroom'},
	[93] = {n = 'pumpkinPie'},
	[94] = {n = 'steakFrites'},
	[95] = {n = 'breadedCutlet'},
	[96] = {n = 'fishAndChips'},
}